### ISSUE TITLE
prechecks.yml playbook should not use 'hosts: all'

### ISSUE THREAD

**Issue by dahorak** [Tendrl/tendrl-ansible#101]
Playbook prechecks.yml should not use `- hosts: all`[1], because the inventory file might contain additional hosts (not only `tendrl_server` and `gluster_servers`, but also for example client machines).

I think, there should be specifically mentioned the used groups, e.g.: 
`- hosts: tendrl_server:gluster_servers`

[1] https://github.com/Tendrl/tendrl-ansible/blob/master/prechecks.yml#L67

**Comment by mbukatov** [comment]
Resolved in https://github.com/Tendrl/tendrl-ansible/pull/102
