### ISSUE TITLE
tendrl2-ansible

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/tendrl-ansible#106]
Tendrl 2 (WIP) will be adding support for Prometheus and Gluster 4.X (more details https://github.com/Tendrl/documentation/wiki/Tendrl-2-Gluster-4.x-(GD2)-Architecture--(WIP) )

It seems that creating a new repository for the additional roles would be a good option. Lets discuss how we can do this

@mbukatov

**Comment by r0h4n** [comment]
@shirshendu @shtripat @nthomas-redhat

**Comment by shtripat** [comment]
Cant we think of having a separate playbook written for tendrl2 and explicitly invoke the same for setting up tendrl2?

**Comment by r0h4n** [comment]
We can think of it, this topic is still open  :)

**Comment by mbukatov** [comment]
Thanks for sharing the architecture on the wiki. I will review it and post my thoughts here.

**Comment by mbukatov** [comment]
If I read the new architecture right, there will be very little to shared between tendrl-ansible for tendrl 1 as it is now and the new tendrl 2. The reusable parts include:

 * etcd setup (but as the etcd is planned to be shared with gd2, reusing current setup without changes is unlikely)
 * ui setup (which is just installation of the package)
 * grafana related setup (but the current ansible tasks assumes integration with carbon and monitoring integration, so this is also unlikely to be reusable without major changes)
 * firewalld setup (the check is fine, but the ports will be different)

Based on this, it seems to me that it would be better to maintain separate tendrl-ansible2 repository.

But before starting this, we need to clarify both high level design choices and few details. I will try to comment on the arch. wip.

**Comment by mbukatov** [comment]
Because of very different architecture of the gd2 stack and it's monitoring, the conclusion is to:

>  maintain separate tendrl-ansible2 repository
