### ISSUE TITLE
tendrl-node-monitoring restart fails

### ISSUE THREAD

**Issue by japplewhite** [Tendrl/tendrl-ansible#12]
ansible-playbook -i gce-hosts -u ajeffrey -b site.yml --limit @site.retry

RUNNING HANDLER [tendrl-storage-node : restart tendrl-node-monitoring] *********
fatal: [stg01]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to start service tendrl-node-monitoring: Job for tendrl-node-monitoring.service failed because start of the service was attempted too often. See \"systemctl status tendrl-node-monitoring.service\" and \"journalctl -xe\" for details.\nTo force a start use \"systemctl reset-failed tendrl-node-monitoring.service\" followed by \"systemctl start tendrl-node-monitoring.service\" again.\n"}

**Comment by japplewhite** [comment]
[root@stg01 ~]# systemctl status tendrl-node-monitoring.service
● tendrl-node-monitoring.service - Daemon to manage tendrl node monitoring
   Loaded: loaded (/usr/lib/systemd/system/tendrl-node-monitoring.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Mon 2017-06-19 17:41:37 UTC; 5min ago
  Process: 14480 ExecStart=/usr/bin/tendrl-node-monitoring (code=exited, status=1/FAILURE)
 Main PID: 14480 (code=exited, status=1/FAILURE)

Jun 19 17:41:37 stg01 systemd[1]: Unit tendrl-node-monitoring.service entered failed state.
Jun 19 17:41:37 stg01 systemd[1]: tendrl-node-monitoring.service failed.
Jun 19 17:41:37 stg01 systemd[1]: tendrl-node-monitoring.service holdoff time over, scheduling restart.
Jun 19 17:41:37 stg01 systemd[1]: start request repeated too quickly for tendrl-node-monitoring.service
Jun 19 17:41:37 stg01 systemd[1]: Failed to start Daemon to manage tendrl node monitoring.
Jun 19 17:41:37 stg01 systemd[1]: Unit tendrl-node-monitoring.service entered failed state.
Jun 19 17:41:37 stg01 systemd[1]: tendrl-node-monitoring.service failed.
Jun 19 17:41:37 stg01 systemd[1]: start request repeated too quickly for tendrl-node-monitoring.service
Jun 19 17:41:37 stg01 systemd[1]: Failed to start Daemon to manage tendrl node monitoring.
Jun 19 17:41:37 stg01 systemd[1]: tendrl-node-monitoring.service failed.

**Comment by japplewhite** [comment]
```
Jun 19 17:50:13 stg01 tendrl-node-monitoring: flows in namespace.tendrl.objects.Service.flowsRegistering object namespace.tendrl.objects.TendrlContextFinding atoms in namespace.tendrl.objects.TendrlContext.atomsFinding flows in namespace.tendrl.objects.TendrlContext.flowsRegistering object namespace.tendrl.objects.DiskFinding atoms in namespace.tendrl.objects.Disk.atomsFinding flows in namespace.tendrl.objects.Disk.flowsRegistering object namespace.tendrl.objects.VirtualDiskFinding atoms in namespace.tendrl.objects.VirtualDisk.atomsFinding flows in namespace.tendrl.objects.VirtualDisk.flowsFinding flows in namespace.tendrl.flowsRegistering flow namespace.tendrl.flows.AuthorizeSshKeyRegistering flow namespace.tendrl.flows.CreateClusterRegistering flow namespace.tendrl.flows.ExpandClusterRegistering flow namespace.tendrl.flows.ImportClusterRegistering flow namespace.tendrl.flows.SetupSshSetup Tendrl definitions (.yml)for namespace.tendrlValidating registered (.py) flows in namespace.tendrl.flowsValidating defined (.yml) flows in namespace.tendrl.flowsValidating registered (.py) objects in namespace.tendrl.objectsValidating defined (.yml) objects in namespace.tendrl.objectsSetup NodeContext for namespace.tendrlLoad definitions (.yml) for namespace.tendrl.objects.NodeContextTraceback (most recent call last):
Jun 19 17:50:13 stg01 tendrl-node-monitoring: File "/usr/bin/tendrl-node-monitoring", line 9, in <module>
Jun 19 17:50:13 stg01 tendrl-node-monitoring: load_entry_point('tendrl-node-monitoring==1.4.2', 'console_scripts', 'tendrl-node-monitoring')()
Jun 19 17:50:13 stg01 tendrl-node-monitoring: File "/usr/lib/python2.7/site-packages/tendrl/node_monitoring/manager/__init__.py", line 24, in main
Jun 19 17:50:13 stg01 tendrl-node-monitoring: TendrlNS()
Jun 19 17:50:13 stg01 tendrl-node-monitoring: File "/usr/lib/python2.7/site-packages/tendrl/commons/__init__.py", line 44, in __init__
Jun 19 17:50:13 stg01 tendrl-node-monitoring: self.setup_common_objects()
Jun 19 17:50:13 stg01 tendrl-node-monitoring: File "/usr/lib/python2.7/site-packages/tendrl/commons/__init__.py", line 280, in setup_common_objects
Jun 19 17:50:13 stg01 tendrl-node-monitoring: self.current_ns.objects.NodeContext()
Jun 19 17:50:13 stg01 tendrl-node-monitoring: File "/usr/lib/python2.7/site-packages/tendrl/commons/objects/node_context/__init__.py", line 28, in __init__
Jun 19 17:50:13 stg01 tendrl-node-monitoring: self.node_id = node_id or self._get_node_id() or self._create_node_id()
Jun 19 17:50:13 stg01 tendrl-node-monitoring: File "/usr/lib/python2.7/site-packages/tendrl/commons/objects/node_context/__init__.py", line 73, in _create_node_id
Jun 19 17:50:13 stg01 tendrl-node-monitoring: NS._int.wclient.write(index_key, node_id, prevExist=False)
Jun 19 17:50:13 stg01 tendrl-node-monitoring: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 500, in write
Jun 19 17:50:13 stg01 tendrl-node-monitoring: response = self.api_execute(path, method, params=params)
Jun 19 17:50:13 stg01 tendrl-node-monitoring: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 907, in wrapper
Jun 19 17:50:13 stg01 tendrl-node-monitoring: return self._handle_server_response(response)
Jun 19 17:50:13 stg01 tendrl-node-monitoring: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 987, in _handle_server_response
Jun 19 17:50:13 stg01 tendrl-node-monitoring: etcd.EtcdError.handle(r)
Jun 19 17:50:13 stg01 tendrl-node-monitoring: File "/usr/lib/python2.7/site-packages/etcd/__init__.py", line 306, in handle
Jun 19 17:50:13 stg01 tendrl-node-monitoring: raise exc(msg, payload)
Jun 19 17:50:13 stg01 tendrl-node-monitoring: etcd.EtcdAlreadyExist: Key already exists : /indexes/machine_id/5e6d9cd23af6f381decb0d58bd927840
Jun 19 17:50:13 stg01 systemd: tendrl-node-monitoring.service: main process exited, code=exited, status=1/FAILURE
Jun 19 17:50:13 stg01 systemd: Unit tendrl-node-monitoring.service entered failed state.
Jun 19 17:50:13 stg01 systemd: tendrl-node-monitoring.service failed.
Jun 19 17:50:13 stg01 systemd: tendrl-node-monitoring.service holdoff time over, scheduling restart.
Jun 19 17:50:13 stg01 systemd: start request repeated too quickly for tendrl-node-monitoring.service
Jun 19 17:50:13 stg01 systemd: Unit tendrl-node-monitoring.service entered failed state.
Jun 19 17:50:13 stg01 systemd: tendrl-node-monitoring.service failed.
```

**Comment by japplewhite** [comment]
@mbukatov  removing /indexes/machine_id/5e6d9cd23af6f381decb0d58bd927840 in etcd resolved the issue

**Comment by mbukatov** [comment]
@japplewhite this looks like an error on node monitoring side: I see unhandled exception in the traceback, which likely caused the service to shutdown and prevented it to start again, but it also suggests that the machine ids were not unique or tainted from previous deployment (I'm just guessing here)? When I rebuild my cluster tomorrow, I could try to reproduce and file an issue on tendrl-node-monitoring (I can't do it right now as I have a previous release deployed and need it for some time).

**Comment by japplewhite** [comment]
@mbukatov yes it was tainted, but only slightly..I never had a working console with any real provisioning or workflows going on. I am testing in GCE now and nodes don't show up for import or cluster creation so that is something I need to file a separate issue on in case the root cause is similar to other disparate hardware environments.

**Comment by mbukatov** [comment]
@japplewhite yeah, there are 2 items for us to handle:

* figure out what was wrong exactly (it seems like non unique machine id or something similar) so that the issue can be reproduced (btw, could you check content of /etc/machine-id on all machines in our environment?)
* file a new issue on tendrl so that this error is detected and reported properly, crashing node monitoring doesn't look good

btw check for machine id will be added into precheck playbook, as noted in https://github.com/Tendrl/tendrl-ansible/issues/7 - I just haven't done that yet as those checks requires more experiments

**Comment by japplewhite** [comment]
@mbukatov filed https://github.com/Tendrl/node-agent/issues/519 for crash

**Comment by japplewhite** [comment]
as to machine-id - bingo - GCE does not guarantee uniqueness
@r0h4n @brainfunked @nthomas-redhat - we have a problem. If a large cloud provider like google does not use unique machine IDs clearly the outside world is not caring about redhat guidelines. Do we really need to base anything on this file? It seems like asking for trouble.

japplewh-OSX:tendrl-ansible japplewh$ ansible all -i gce-hosts -m shell -a 'cat /etc/machine-id'
tendrl | SUCCESS | rc=0 >>
5e6d9cd23af6f381decb0d58bd927840

stg03 | SUCCESS | rc=0 >>
5e6d9cd23af6f381decb0d58bd927840

stg02 | SUCCESS | rc=0 >>
5e6d9cd23af6f381decb0d58bd927840

stg01 | SUCCESS | rc=0 >>
5e6d9cd23af6f381decb0d58bd927840

**Comment by japplewhite** [comment]
a workaround would be to require this in ansible setup playbook
`sudo rm /etc/machine-id`
`sudo systemd-machine-id-setup`

problem would be when someone is actually using this for some reason..would be fine on new nodes for create cluster but problematic for registered nodes. @mbukatov - Maybe the best solution is to check for duplicates in the pre-check and run the above two commands if dups are found

**Comment by brainfunked** [comment]
The virtualization platforms don't alter the contents within the images when cloning. Ensuring the unique machine id would thus have to be an administrator responsibility. Rather than directly modifying the machine ids in question, I think the playbooks should exit with an error displaying the list of duplicate ids and direct the user to run the machine id regeneration module (which essentially runs the above commands) to fix the errors.

**Comment by japplewhite** [comment]
@mbukatov @brainfunked I am ok with the exit and notify - lets include the two suggested commands to be run as in my comment above so they can get to it. Most admins are not familiar with machine-id in my experience. I never once used it in all the years I worked as a sysadmin - maybe it's becoming more prevalent but certainly not widespread

**Comment by mbukatov** [comment]
Based on further investigation, this is not an issue of tendrl-ansible. See  https://github.com/Tendrl/node-agent/issues/519
