### ISSUE TITLE
Update packages produces unfinished transactions error

### ISSUE THREAD

**Issue by japplewhite** [Tendrl/tendrl-ansible#13]
again - in GCE env 

japplewh-OSX:tendrl-ansible japplewh$ ansible-playbook  -i gce-inventory  -b site.yml

produces..
<snip>
TASK [Update all installed packages] *******************************************
ok: [tendrl]
fatal: [stg-nodes-group-c3n7]: FAILED! => {"changed": true, "failed": true, "msg": "There are unfinished transactions remaining. You might consider running yum-complete-transaction, or \"yum-complete-transaction --cleanup-only\" and \"yum history redo last\", first to finish them. If those don't work you'll have to try removing/installing packages by hand (maybe package-cleanup can help).\nThe program yum-complete-transaction is found in the yum-utils package.\nError:  Multilib version problems found. This often means that the root\n       cause is something else and multilib version checking is just\n       pointing out that there is a problem. Eg.:\n       \n         1. You have an upgrade for glibc which is missing some\n            dependency that another package requires. Yum is trying to\n            solve this by installing an older version of glibc of the\n            different architecture. If you exclude the bad architecture\n            yum will tell you what the root cause is (which package\n            requires what). You can try redoing the upgrade with\n            --exclude glibc.otherarch ... this should give you an error\n            message showing the root cause of the problem.\n       \n         2. You have multiple architectures of glibc installed, but\n            yum can only see an upgrade for one of those architectures.\n            If you don't want/need both architectures anymore then you\n            can remove the one with the missing update and everything\n            will work.\n       \n         3. You have duplicate versions of glibc installed already.\n            You can use \"yum check\" to get yum show these errors.\n       \n       ...you can also use --setopt=protected_multilib=false to remove\n       this checking, however this is almost never the correct thing to\n       do as something else is very likely to go wrong (often causing\n       much more problems).\n       \n       Protected multilib versions: glibc-2.17-157.el7_3.2.x86_64 != glibc-2.17-157.el7_3.1.i686\n", "rc": 1, "results": ["Loaded plugins: fastestmirror\nLoading mirror speeds from cached hostfile\n * base: repos.forethought.net\n * epel: mirror.steadfast.net\n * extras: centos.mbni.med.umich.edu\n * updates: mirror.cisp.com\nResolving Dependencies\n--> Running transaction check\n---> Package NetworkManager.x86_64 1:1.4.0-19.el7_3 will be updated\n---> Package NetworkManager.x86_64 1:1.4.0-20.el7_3 will be an update\n---> Package NetworkManager-adsl.x86_64 1:1.4.0-19.el7_3 will be updated\n---> Package NetworkManager-adsl.x86_64 1:1.4.0-20.el7_3 will be an update\n---> Package NetworkManager-bluetooth.x86_64 1:1.4.0-19.el7_3 will be updated\n---> Package NetworkManager-bluetooth.x86_64 1:1.4.0-20.el7_3 will be an update\n---> Package NetworkManager-glib.x86_64 1:1.4.0-19.el7_3 will be updated\n---> Package NetworkManager-glib.x86_64 1:1.4.0-20.el7_3 will be an update\n---> Package NetworkManager-libnm.x86_64 1:1.4.0-19.el7_3 will be updated\n---> Package NetworkManager-libnm.x86_64 1:1.4.0-20.el7_3 will be an update\n---> Package NetworkManager-team.x86_64 1:1.4.0-19.el7_3 will be updated\n---> Package NetworkManager-team.x86_64 1:1.4.0-20.el7_3 will be an update\n---> Package NetworkManager-tui.x86_64 1:1.4.0-19.el7_3 will be updated\n---> Package NetworkManager-tui.x86_64 1:1.4.0-20.el7_3 will be an update\n---> Package NetworkManager-wifi.x86_64 1:1.4.0-19.el7_3 will be updated\n---> Package NetworkManager-wifi.x86_64 1:1.4.0-20.el7_3 will be an update\n---> Package NetworkManager-wwan.x86_64 1:1.4.0-19.el7_3 will be updated\n---> Package NetworkManager-wwan.x86_64 1:1.4.0-20.el7_3 will be an update\n---> Package ca-certificates.noarch 0:2017.2.11-70.1.el7_3 will be updated\n---> Package ca-certificates.noarch 0:2017.2.14-70.1.el7_3 will be an update\n---> Package dracut.x86_64 0:033-463.el7 will be updated\n---> Package dracut.x86_64 0:033-463.el7_3.1 will be an update\n---> Package dracut-config-rescue.x86_64 0:033-463.el7 will be updated\n---> Package dracut-config-rescue.x86_64 0:033-463.el7_3.1 will be an update\n---> Package firewalld.noarch 0:0.4.3.2-8.1.el7_3.2 will be updated\n---> Package firewalld.noarch 0:0.4.3.2-8.1.el7_3.3 will be an update\n---> Package firewalld-filesystem.noarch 0:0.4.3.2-8.1.el7_3.2 will be updated\n---> Package firewalld-filesystem.noarch 0:0.4.3.2-8.1.el7_3.3 will be an update\n---> Package glibc.x86_64 0:2.17-157.el7_3.1 will be updated\n--> Processing Dependency: glibc = 2.17-157.el7_3.1 for package: glibc-common-2.17-157.el7_3.1.x86_64\n---> Package glibc.x86_64 0:2.17-157.el7_3.2 will be an update\n---> Package google-cloud-sdk.noarch 0:155.0.0-1.el7 will be updated\n---> Package google-cloud-sdk.noarch 0:159.0.0-1.el7 will be an update\n---> Package google-compute-engine.noarch 0:2.3.7-0.1495559176.el7 will be updated\n---> Package google-compute-engine.noarch 0:2.4.0-0.1497053016.el7 will be an update\n---> Package kernel.x86_64 0:3.10.0-514.21.1.el7 will be installed\n---> Package kernel-tools.x86_64 0:3.10.0-514.16.1.el7 will be updated\n---> Package kernel-tools.x86_64 0:3.10.0-514.21.1.el7 will be an update\n---> Package kernel-tools-libs.x86_64 0:3.10.0-514.16.1.el7 will be updated\n---> Package kernel-tools-libs.x86_64 0:3.10.0-514.21.1.el7 will be an update\n---> Package kpartx.x86_64 0:0.4.9-99.el7_3.1 will be updated\n---> Package kpartx.x86_64 0:0.4.9-99.el7_3.3 will be an update\n---> Package libgudev1.x86_64 0:219-30.el7_3.8 will be updated\n---> Package libgudev1.x86_64 0:219-30.el7_3.9 will be an update\n---> Package libnetfilter_conntrack.x86_64 0:1.0.4-2.el7 will be updated\n---> Package libnetfilter_conntrack.x86_64 0:1.0.6-1.el7_3 will be an update\n---> Package nss.x86_64 0:3.28.4-1.0.el7_3 will be updated\n---> Package nss.x86_64 0:3.28.4-1.2.el7_3 will be an update\n---> Package nss-sysinit.x86_64 0:3.28.4-1.0.el7_3 will be updated\n---> Package nss-sysinit.x86_64 0:3.28.4-1.2.el7_3 will be an update\n---> Package nss-tools.x86_64 0:3.28.4-1.0.el7_3 will be updated\n---> Package nss-tools.x86_64 0:3.28.4-1.2.el7_3 will be an update\n---> Package polkit.x86_64 0:0.112-11.el7_3 will be updated\n---> Package polkit.x86_64 0:0.112-12.el7_3 will be an update\n---> Package python-firewall.noarch 0:0.4.3.2-8.1.el7_3.2 will be updated\n---> Package python-firewall.noarch 0:0.4.3.2-8.1.el7_3.3 will be an update\n---> Package python-perf.x86_64 0:3.10.0-514.16.1.el7 will be updated\n---> Package python-perf.x86_64 0:3.10.0-514.21.1.el7 will be an update\n---> Package sudo.x86_64 0:1.8.6p7-21.el7_3 will be updated\n---> Package sudo.x86_64 0:1.8.6p7-22.el7_3 will be an update\n---> Package systemd.x86_64 0:219-30.el7_3.8 will be updated\n---> Package systemd.x86_64 0:219-30.el7_3.9 will be an update\n---> Package systemd-libs.x86_64 0:219-30.el7_3.8 will be updated\n---> Package systemd-libs.x86_64 0:219-30.el7_3.9 will be an update\n---> Package systemd-sysv.x86_64 0:219-30.el7_3.8 will be updated\n---> Package systemd-sysv.x86_64 0:219-30.el7_3.9 will be an update\n---> Package tuned.noarch 0:2.7.1-3.el7_3.1 will be updated\n---> Package tuned.noarch 0:2.7.1-3.el7_3.2 will be an update\n--> Running transaction check\n---> Package glibc.i686 0:2.17-157.el7_3.1 will be installed\n--> Processing Dependency: libfreebl3.so(NSSRAWHASH_3.12.3) for package: glibc-2.17-157.el7_3.1.i686\n--> Processing Dependency: libfreebl3.so for package: glibc-2.17-157.el7_3.1.i686\n---> Package glibc.x86_64 0:2.17-157.el7_3.1 will be updated\n--> Running transaction check\n---> Package nss-softokn-freebl.i686 0:3.16.2.3-14.4.el7 will be installed\n--> Finished Dependency Resolution\n"]}

**Comment by japplewhite** [comment]
seems glibc update somehow went bad

I could get a manual yum update to run only after
`yum remove glibc-common-2.17-157.el7_3.2.x86_64`
because glibc-common-2.17-157.el7_3.1.x86_64 was also installed

then the updates went through

**Comment by mbukatov** [comment]
As can be seen in expanded, more readable, version of the previous output:

```
There are unfinished transactions remaining. You might consider running yum-complete-transaction, or \"yum-complete-transaction --cleanup-only\" and \"yum history redo last\", first to finish them. If those don't work you'll have to try removing/installing packages by hand (maybe package-cleanup can help).
The program yum-complete-transaction is found in the yum-utils package.
Error:  Multilib version problems found. This often means that the root
       cause is something else and multilib version checking is just
       pointing out that there is a problem. Eg.:
       
         1. You have an upgrade for glibc which is missing some
            dependency that another package requires. Yum is trying to
            solve this by installing an older version of glibc of the
            different architecture. If you exclude the bad architecture
            yum will tell you what the root cause is (which package
            requires what). You can try redoing the upgrade with
            --exclude glibc.otherarch ... this should give you an error
            message showing the root cause of the problem.
       
         2. You have multiple architectures of glibc installed, but
            yum can only see an upgrade for one of those architectures.
            If you don't want/need both architectures anymore then you
            can remove the one with the missing update and everything
            will work.
       
         3. You have duplicate versions of glibc installed already.
            You can use \"yum check\" to get yum show these errors.
       
       ...you can also use --setopt=protected_multilib=false to remove
       this checking, however this is almost never the correct thing to
       do as something else is very likely to go wrong (often causing
       much more problems).
       
       Protected multilib versions: glibc-2.17-157.el7_3.2.x86_64 != glibc-2.17-157.el7_3.1.i686
", "rc": 1, "results": ["Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: repos.forethought.net
 * epel: mirror.steadfast.net
 * extras: centos.mbni.med.umich.edu
 * updates: mirror.cisp.com
Resolving Dependencies
--> Running transaction check
---> Package NetworkManager.x86_64 1:1.4.0-19.el7_3 will be updated
---> Package NetworkManager.x86_64 1:1.4.0-20.el7_3 will be an update
---> Package NetworkManager-adsl.x86_64 1:1.4.0-19.el7_3 will be updated
---> Package NetworkManager-adsl.x86_64 1:1.4.0-20.el7_3 will be an update
---> Package NetworkManager-bluetooth.x86_64 1:1.4.0-19.el7_3 will be updated
---> Package NetworkManager-bluetooth.x86_64 1:1.4.0-20.el7_3 will be an update
---> Package NetworkManager-glib.x86_64 1:1.4.0-19.el7_3 will be updated
---> Package NetworkManager-glib.x86_64 1:1.4.0-20.el7_3 will be an update
---> Package NetworkManager-libnm.x86_64 1:1.4.0-19.el7_3 will be updated
---> Package NetworkManager-libnm.x86_64 1:1.4.0-20.el7_3 will be an update
---> Package NetworkManager-team.x86_64 1:1.4.0-19.el7_3 will be updated
---> Package NetworkManager-team.x86_64 1:1.4.0-20.el7_3 will be an update
---> Package NetworkManager-tui.x86_64 1:1.4.0-19.el7_3 will be updated
---> Package NetworkManager-tui.x86_64 1:1.4.0-20.el7_3 will be an update
---> Package NetworkManager-wifi.x86_64 1:1.4.0-19.el7_3 will be updated
---> Package NetworkManager-wifi.x86_64 1:1.4.0-20.el7_3 will be an update
---> Package NetworkManager-wwan.x86_64 1:1.4.0-19.el7_3 will be updated
---> Package NetworkManager-wwan.x86_64 1:1.4.0-20.el7_3 will be an update
---> Package ca-certificates.noarch 0:2017.2.11-70.1.el7_3 will be updated
---> Package ca-certificates.noarch 0:2017.2.14-70.1.el7_3 will be an update
---> Package dracut.x86_64 0:033-463.el7 will be updated
---> Package dracut.x86_64 0:033-463.el7_3.1 will be an update
---> Package dracut-config-rescue.x86_64 0:033-463.el7 will be updated
---> Package dracut-config-rescue.x86_64 0:033-463.el7_3.1 will be an update
---> Package firewalld.noarch 0:0.4.3.2-8.1.el7_3.2 will be updated
---> Package firewalld.noarch 0:0.4.3.2-8.1.el7_3.3 will be an update
---> Package firewalld-filesystem.noarch 0:0.4.3.2-8.1.el7_3.2 will be updated
---> Package firewalld-filesystem.noarch 0:0.4.3.2-8.1.el7_3.3 will be an update
---> Package glibc.x86_64 0:2.17-157.el7_3.1 will be updated
--> Processing Dependency: glibc = 2.17-157.el7_3.1 for package: glibc-common-2.17-157.el7_3.1.x86_64
---> Package glibc.x86_64 0:2.17-157.el7_3.2 will be an update
---> Package google-cloud-sdk.noarch 0:155.0.0-1.el7 will be updated
---> Package google-cloud-sdk.noarch 0:159.0.0-1.el7 will be an update
---> Package google-compute-engine.noarch 0:2.3.7-0.1495559176.el7 will be updated
---> Package google-compute-engine.noarch 0:2.4.0-0.1497053016.el7 will be an update
---> Package kernel.x86_64 0:3.10.0-514.21.1.el7 will be installed
---> Package kernel-tools.x86_64 0:3.10.0-514.16.1.el7 will be updated
---> Package kernel-tools.x86_64 0:3.10.0-514.21.1.el7 will be an update
---> Package kernel-tools-libs.x86_64 0:3.10.0-514.16.1.el7 will be updated
---> Package kernel-tools-libs.x86_64 0:3.10.0-514.21.1.el7 will be an update
---> Package kpartx.x86_64 0:0.4.9-99.el7_3.1 will be updated
---> Package kpartx.x86_64 0:0.4.9-99.el7_3.3 will be an update
---> Package libgudev1.x86_64 0:219-30.el7_3.8 will be updated
---> Package libgudev1.x86_64 0:219-30.el7_3.9 will be an update
---> Package libnetfilter_conntrack.x86_64 0:1.0.4-2.el7 will be updated
---> Package libnetfilter_conntrack.x86_64 0:1.0.6-1.el7_3 will be an update
---> Package nss.x86_64 0:3.28.4-1.0.el7_3 will be updated
---> Package nss.x86_64 0:3.28.4-1.2.el7_3 will be an update
---> Package nss-sysinit.x86_64 0:3.28.4-1.0.el7_3 will be updated
---> Package nss-sysinit.x86_64 0:3.28.4-1.2.el7_3 will be an update
---> Package nss-tools.x86_64 0:3.28.4-1.0.el7_3 will be updated
---> Package nss-tools.x86_64 0:3.28.4-1.2.el7_3 will be an update
---> Package polkit.x86_64 0:0.112-11.el7_3 will be updated
---> Package polkit.x86_64 0:0.112-12.el7_3 will be an update
---> Package python-firewall.noarch 0:0.4.3.2-8.1.el7_3.2 will be updated
---> Package python-firewall.noarch 0:0.4.3.2-8.1.el7_3.3 will be an update
---> Package python-perf.x86_64 0:3.10.0-514.16.1.el7 will be updated
---> Package python-perf.x86_64 0:3.10.0-514.21.1.el7 will be an update
---> Package sudo.x86_64 0:1.8.6p7-21.el7_3 will be updated
---> Package sudo.x86_64 0:1.8.6p7-22.el7_3 will be an update
---> Package systemd.x86_64 0:219-30.el7_3.8 will be updated
---> Package systemd.x86_64 0:219-30.el7_3.9 will be an update
---> Package systemd-libs.x86_64 0:219-30.el7_3.8 will be updated
---> Package systemd-libs.x86_64 0:219-30.el7_3.9 will be an update
---> Package systemd-sysv.x86_64 0:219-30.el7_3.8 will be updated
---> Package systemd-sysv.x86_64 0:219-30.el7_3.9 will be an update
---> Package tuned.noarch 0:2.7.1-3.el7_3.1 will be updated
---> Package tuned.noarch 0:2.7.1-3.el7_3.2 will be an update
--> Running transaction check
---> Package glibc.i686 0:2.17-157.el7_3.1 will be installed
--> Processing Dependency: libfreebl3.so(NSSRAWHASH_3.12.3) for package: glibc-2.17-157.el7_3.1.i686
--> Processing Dependency: libfreebl3.so for package: glibc-2.17-157.el7_3.1.i686
---> Package glibc.x86_64 0:2.17-157.el7_3.1 will be updated
--> Running transaction check
---> Package nss-softokn-freebl.i686 0:3.16.2.3-14.4.el7 will be installed
--> Finished Dependency Resolution
```

The problems here are:

* unfinished yum transactions are present on the machine
* the machine has multilib problem: glibc-2.17-157.el7_3.2.x86_64 != glibc-2.17-157.el7_3.1.i686

Since we can't expect ansible yum module to work on a machine in such incorrect state, I don't think that this is a problem on tendrl-ansible side.

**Comment by mbukatov** [comment]
Based on my previous comment, I'm closing this issue.
