### ISSUE TITLE
Building packages from `master` branch doesn't work recently

### ISSUE THREAD

**Issue by dahorak** [Tendrl/tendrl-ansible#132]
There seems to be some problem with [version](https://github.com/Tendrl/tendrl-ansible/blob/master/tendrl-ansible.spec#L6) in spec file in `master` branch, which causes failing builds in CentOS CI.

The problem seems to be with the `a` at the end of the *version* string.

The particular error is:
```
tar caf tendrl-ansible-1.6.3.tar.gz tendrl-ansible-1.6.3
fedpkg --dist epel7 srpm
sources file doesn't exist. Source files download skipped.
error: File /tmp/build-tendrl-tendrl-ansible.HJY5wUvfTF/tendrl-ansible/tendrl-ansible-1.6.3a.tar.gz: No such file or directory

Could not execute srpm: Failed to execute command.
make: *** [srpm] Error 1
```
Full output for example: https://ci.centos.org/view/tendrl/job/tendrl-build-1-master-tendrl-ansible/58/console

List of (failing) jobs: https://ci.centos.org/view/tendrl/job/tendrl-build-1-master-tendrl-ansible/

**Comment by mbukatov** [comment]
Right. The problem is that when Tendrl upstream doesn't do any release at all, and uses minor version for a major version, I have no much space to bump version in a spec file. I will probably just use `Release` field, but will give hacking the build script a try.

**Comment by mbukatov** [comment]
Ok, it's really fixed: https://ci.centos.org/view/tendrl/job/tendrl-build-1-master-tendrl-ansible/61/
