### ISSUE TITLE
 Need to change graphite db initialization command in tendrl-ansible as per new graphite-web version-1.1.4-1

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/tendrl-ansible#133]
We are moving graphite-web from 0.9.X to 1.1.4-1. So as per the new version of graphite-web sync DB initialization should be changed in tendrl-ansible.

**Comment by mbukatov** [comment]
Implemented via https://github.com/Tendrl/tendrl-ansible/pull/134
