### ISSUE TITLE
tendrl - import cluster failed

### ISSUE THREAD

**Issue by deckardbsd** [Tendrl/tendrl-ansible#141]
Hello,
I've installed tendrl using ansible and I'm trying to import a glusterfs cluster, but I'm unable.
It fails with the following error:

`Failure in Job 0dda959d-ef74-42c2-8e20-5592bd4f35da Flow tendrl.flows.ImportCluster with error: Traceback (most recent call last): File "/usr/lib/python2.7/site-packages/tendrl/commons/jobs/__init__.py", line 240, in process_job the_flow.run() File "/usr/lib/python2.7/site-packages/tendrl/commons/flows/import_cluster/__init__.py", line 131, in run exc_traceback) FlowExecutionFailedError: ['Traceback (most recent call last):\n', ' File "/usr/lib/python2.7/site-packages/tendrl/commons/flows/import_cluster/__init__.py", line 98, in run\n super(ImportCluster, self).run()\n', ' File "/usr/lib/python2.7/site-packages/tendrl/commons/flows/__init__.py", line 227, in run\n "Error executing post run function: %s" % atom_fqn\n', 'AtomExecutionFailedError: Atom Execution failed. Error: Error executing post run function: tendrl.objects.Cluster.atoms.SetupClusterAlias\n'] `

Any ideea what might cause this ?

**Comment by mbukatov** [comment]
@GowthamShanmugam Could you transfer this issue to tendrl-commons? Also, do you have any idea what could go wrong in this case?

**Comment by GowthamShanmugam** [comment]
Please check tendr-monitoring-integration service is running on tendrl-server

   service tendrl-monitoring-integration status


If it is already running then please check /tmp directory have execution permission, if not please assign execution permission.

**Comment by deckardbsd** [comment]
The service is running and /tmp has execution permission.
journalctl -u tendrl-monitoring-integration:
`Unable to pass the message into socket.{"integration_id": null, "publisher": "monitoring_integration", "job_id": null, "timestamp": "2019-03-28T16:57:24.676829+00:00", "caller": {"function": "load_definition", "line_no": 50, "filename ...`

**Comment by GowthamShanmugam** [comment]
Is packages are installed from release repo or master repo (https://github.com/Tendrl/tendrl-ansible/blob/master/roles/tendrl-ansible.tendrl-copr/defaults/main.yml).

If it is "release branch" repo then please check "server node" and "storage-node"  ansible version is ansible >= 2.5

**Comment by deckardbsd** [comment]
Ok, is working now, although I cannot see the dashboard.
When I click on "dashboard" I get:

`
{{alert.title}}

    Docs
    Support Plans
    Community
    Grafana v4.6.5 (commit: b3c8708)
    New version available!

`
