### ISSUE TITLE
Need ansible playbook for grafana and monitoring-integration

### ISSUE THREAD

**Issue by TimothyAsir** [Tendrl/tendrl-ansible#18]
Add ansible playbook for installing and configuring grafana and monitoring-integration.
This installation should do the 1) basic configuration based on the default values and
the given variables, 2) should start the grafana-server service and the monitoring-
integration.

**Comment by mbukatov** [comment]
~ok, let's start with updating the wikipage here first:~

~https://github.com/Tendrl/documentation/wiki/Tendrl-Package-Installation-Reference~

**Comment by mbukatov** [comment]
linking related spec draft: https://github.com/Tendrl/specifications/issues/175 https://github.com/Tendrl/specifications/pull/202

**Comment by sankarshanmukhopadhyay** [comment]
I would state that we should not modify the wikipage at https://github.com/Tendrl/documentation/wiki/Tendrl-Package-Installation-Reference - this continues to be a valid and correct way to install and configure the complete Tendrl stack for the composite (Day1+Day2+Day3) usage. The existing playbooks in tendrl-ansible are expected to complete the task as written down in this page.

For specifically setting up a form of Tendrl scoped for Day3, it might be good to have a new page (as a working page) and begin from there.

@Tendrl/tendrl-core : please provide your feedback on this.

**Comment by cybernth** [comment]
Agree. We can start new wiki page which describes the install & setup procedure for Tendrl scoped for Day3

**Comment by brainfunked** [comment]
I think the spec should document the deployment details for an upcoming implementation. A corresponding documentation issue should be tracked via the spec. The wiki being a reference for the 'current' implementation should be updated only once the new implementation is actually merged. The spec can be closed only after the documentation has been updated.

**Comment by mbukatov** [comment]
See also:

* https://github.com/Tendrl/documentation/wiki/Tendrl-Package-Installation-Reference(Revised)
* https://github.com/Tendrl/documentation/wiki/Tendrl-release-v1.5.0-(summary)

**Comment by mbukatov** [comment]
Addressed in https://github.com/Tendrl/tendrl-ansible/pull/22
