### ISSUE TITLE
Remove node-monitoring and performance-monitoring installation steps

### ISSUE THREAD

**Issue by anmolbabu** [Tendrl/tendrl-ansible#20]
Based on https://github.com/Tendrl/specifications/issues/204 and https://github.com/Tendrl/specifications/issues/179 these services are going to be removed and accordingly changes need to be made in tendrl-ansible

**Comment by mbukatov** [comment]
Ack, thanks for linking the specs here.

**Comment by mbukatov** [comment]
Addressed in https://github.com/Tendrl/tendrl-ansible/pull/22
