### ISSUE TITLE
User does not need to configure any tags in Tendrl configuration

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/tendrl-ansible#27]
Role "tendrl-storage-node"  contains steps to add "provisioner/gluster" tag for tendrl-node-agents on Gluster storage nodes.

details: https://github.com/Tendrl/tendrl-ansible/blob/master/roles/tendrl-storage-node/tasks/tendrl-node-agent.yml#L21

From tendrl-release 1.5.1 [0], configuration of above tag  will not be required since it is automatically done during ImportCluster API call by tendrl backend.

Please remove "Add provisioner/gluster tag into node-agent.conf.yaml"  from above playbook

 \[0\] : https://github.com/Tendrl/documentation/wiki/Tendrl-release-v1.5.1-(install-guide)

**Comment by mbukatov** [comment]
@r0h4n Additional question: should I keep the following line in site.yml.sample (see the reference below for full context)?

https://github.com/Tendrl/tendrl-ansible/blob/e0015976d5951acad431fb266fcbd48583a47e77/site.yml.sample#L98

I could either add an explanation or just remove it altogether. During work on 1.5.1, I just commented it out.

**Comment by mbukatov** [comment]
Fixed in https://github.com/Tendrl/tendrl-ansible/pull/28
