### ISSUE TITLE
Replacing grafana.ini file path in  /etc/sysconfig/grafana-server

### ISSUE THREAD

**Issue by rishubhjain** [Tendrl/tendrl-ansible#29]
With reference to https://github.com/Tendrl/monitoring-integration/issues/60, there is a need for ansible script to replace the path of grafana.ini file in `/etc/sysconfig/grafana-server` file.
The path to all configuration files are present  in grafana-server file https://github.com/grafana/grafana/blob/master/packaging/rpm/sysconfig/grafana-server
When grafana is installed this file is copied to `/etc/sysconfig/grafana-server.`

Grafana is installed when monitoring-integration is installed, so this change needs to be made after monitoring-integration is installed and before grafana-server.service is started

The new path in `/etc/sysconfig/grafana-server` will be:

```
CONF_DIR=/etc/tendrl/monitoring-integration/grafana/
CONF_FILE=/etc/tendrl/monitoring-integration/grafana/grafana.ini 
```

**Comment by mbukatov** [comment]
Ok, so we will ship grafana config files in monitoring-integration without overriding original grafana config file, and we will switch grafana to use tendrl config by editing [sysconfig environment](https://fedoraproject.org/wiki/Packaging:Systemd#EnvironmentFiles_and_support_for_.2Fetc.2Fsysconfig_files) file instead. This doesn't seem (at least at first sight) to conflict with any packaging guide I'm aware of.

**Comment by mbukatov** [comment]
I guess that we need to check what would happen when grafana is updated. This is more important as grafana packaging is out of our control.

**Comment by mbukatov** [comment]
@rishubhjain you can check proposed changes in linked pull request, but latest snapshot build `tendrl-monitoring-integration-1.5.1-20170908T124712.dadabad.noarch` doesn't provide grafana.ini file in new place `/etc/tendrl/monitoring-integration/grafana/grafana.ini` yet

**Comment by mbukatov** [comment]
Addressed in https://github.com/Tendrl/tendrl-ansible/pull/31
