### ISSUE TITLE
Generating random password and setting it in grafana.ini and monitoring-integration.conf.yaml

### ISSUE THREAD

**Issue by rishubhjain** [Tendrl/tendrl-ansible#32]
Tendrl ansible is supposed to generate a random password for grafana admin, which is then supposed to be inserted into grafana.ini and monitoring-integration.conf.yaml

In monitoring-integration it is supposed to be inserted under credentials under password
https://github.com/Tendrl/monitoring-integration/blob/master/etc/tendrl/monitoring-integration/monitoring-integration.conf.yaml.sample#L27

In Grafana.ini
It should be set under admin_password
https://github.com/Tendrl/monitoring-integration/blob/master/etc/grafana/grafana.ini#L146

**Comment by rishubhjain** [comment]
@mbukatov Please consider this functionality and make appropriate changes

**Comment by rishubhjain** [comment]
@mbukatov Any progress on this issue?, Would you require any other details regarding this issue?

**Comment by mbukatov** [comment]
I'm going to use the same approach as used for setting etcd authentication: ansible password lookup plugin

**Comment by mbukatov** [comment]
Implemented in https://github.com/Tendrl/tendrl-ansible/pull/36
