### ISSUE TITLE
Enable etcd user and password based authentication

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/tendrl-ansible#34]
Etcd is installed on the Tendrl server node. Tendrl now supports authenticating to etcd via username and password.

Please follow below changes to Tendrl install guide and adopt them to support etcd auth via tendrl-ansible 

https://github.com/Tendrl/documentation/wiki/Tendrl-release-v1.5.2-(install-guide)/_compare/ccfe848ff6b1757cfa1362f58dca07be094bc22c...39c606e51badd1572aea337665c1cfc0e057c3f6

**Comment by mbukatov** [comment]
Ok, so I need to generate new password via ansible first:

```
$ cat password.yml                                                                                                     
---                                                                                                                    
- hosts: localhost
  connection: local
  tasks:
    - debug: msg="{{ lookup('password', '/dev/null chars=ascii_letters length=30') }}"

```

https://docs.ansible.com/ansible/latest/playbooks_lookups.html#the-password-lookup

**Comment by mbukatov** [comment]
There is no ansible module for etcdctl, so I need to test if it's ok to run these commands over and over again.

**Comment by mbukatov** [comment]
@r0h4n what file do you mean by this:

> Add the etcd_username and etcd_password to all Tendrl service config file

At this point, only etcd is installed, so I would assume that the changes in tendrl config files are described later on, as we install and configure them.

**Comment by r0h4n** [comment]
@mbukatov Keep this entire auth thing optional, user should be able to run unsafe etcd too (for devs/testing etc)

**Comment by mbukatov** [comment]
@r0h4n ok, let's have an ansible variable to control this, with auth enabled as a default (so that for dev/testing, one can turn it off)

**Comment by mbukatov** [comment]
~Blocked~ Keeping etcd auth disabled is blocked by https://github.com/Tendrl/api/issues/294 (I updated the pull request so that enabling etcd auth will work, but disabling will not, until https://github.com/Tendrl/api/issues/294 is fixed).

**Comment by mbukatov** [comment]
Addressed in https://github.com/Tendrl/tendrl-ansible/pull/35

But as pointed out in a previous comment, it's not possible to start with etcd auth disabled until https://github.com/Tendrl/api/issues/294 is fixed.
