### ISSUE TITLE
Relicense from Apache 2.0 to LGPL 2.1

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/tendrl-ansible#38]
As pointed out by @r0h4n , we need to align license of tendrl-ansible with the rest of Tendrl project, which means relicensing to [LGPL 2.1](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.html).

Approval for this is needed from all contributors:

* [X] @mbukatov
* [x] @dahorak 
* [x] @japplewhite 
* [x] @brainfunked 

If you find yourself in this list, please add "+1" reaction or add a comment with "I agree" text below. I will monitor the approvals, update the list and when all contributors agree, will go on and change the license.

**Comment by dahorak** [comment]
+1

**Comment by japplewhite** [comment]
+1

**Comment by brainfunked** [comment]
+1

**Comment by mbukatov** [comment]
The license has been changed in 738b812e4f083cc56c78e995a06fef6b1ffbc28c
