### ISSUE TITLE
RPM builds required

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/tendrl-ansible#40]
Please add rpm spec file and any other files (makefile etc) required for enabling copr (master branch and release branch) rpm builds for tendrl-ansible

**Comment by r0h4n** [comment]
cc @dahorak

**Comment by mbukatov** [comment]
Package should follow the same scheme as used for [Red Hat Enterprise Linux (RHEL) System Roles](https://access.redhat.com/articles/3050101)

**Comment by mbukatov** [comment]
Initial implementation from https://github.com/Tendrl/tendrl-ansible/pull/47 merged
