### ISSUE TITLE
Configuration of cert based etcd auth

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/tendrl-ansible#42]
Based on poor performance of etcd password authentication, we are going to use authentication based on certificates instead.

## The Setup

* issue cert for each storage node and a tendrl server (we could go further and issue cert for each service, but that would be even more work) (outside of tendrl-ansible)
* deploy the cert files on all machines (outside of tendrl-ansible)
* reconfigure etcd for client auth
   - what to change?
       * --cert-file=/path/to/server.crt
       * --key-file=/path/to/server.key
        * --client-cert-auth --trusted-ca-file=/path/to/ca.crt
   - where to expect the cert files? see https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/security_guide/sec-using_openssl
* update config file of all tendrl services (parametrized via variable)
* restart all tendrl and etcd service

## Details

@r0h4n describes the setup in our wiki: https://github.com/Tendrl/documentation/wiki/Tendrl-with-a-secure-etcd-cluster

Possible missing details in the description:

* `ETCD_CLIENT_CERT_AUTH="true"`
* setup for tendrl-api

## See Also

* https://coreos.com/etcd/docs/latest/op-guide/security.html
* https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/security_guide/sec-using_openssl

## Related Issues

* Previous `tendrl-ansible` issue for password auth, which is being replaced by this cert base approach: https://github.com/Tendrl/tendrl-ansible/issues/34
* https://github.com/Tendrl/commons/issues/721 (this issue references the wikipage linked above)
* https://github.com/Tendrl/api/issues/262

## Blocking Issues

These issues blocks merge of this into master:

* https://github.com/Tendrl/api/issues/307 (implemented, verification pending)
* https://github.com/Tendrl/monitoring-integration/issues/170 (merged)
* https://github.com/Tendrl/notifier/issues/128 (fixed)
* https://github.com/Tendrl/node-agent/issues/640
  which is blocked by: https://bugzilla.redhat.com/show_bug.cgi?id=1251583
  will be resolved by removing gevent: see https://github.com/Tendrl/commons/issues/751

**Comment by mbukatov** [comment]
@sidhax this seems like security related issue

**Comment by mbukatov** [comment]
Note to self, here is an example of using etcdctl with client-server tls auth:

```
# etcdctl --ca-file /etc/pki/tls/certs/ca-usmqe.crt --cert-file /etc/pki/tls/certs/etcd.crt --key-file /etc/pki/tls/private/etcd.key --endpoints https://${HOSTNAME}:2379 ls /
/indexes
/messages
/queue
/clusters
/networks
/nodes
/notifications
/alerting
```

Or from some storage machine via curl:

```
# curl --cacert /etc/pki/tls/certs/ca-usmqe.crt --cert /etc/pki/tls/certs/etcd.crt --key /etc/pki/tls/private/etcd.key https://mbukatov-usm1-server.usmqe.lab.eng.brq.redhat.com:2379/v2/keys/
{"action":"get","node":{"dir":true,"nodes":[{"key":"/alerting","dir":true,"modifiedIndex":430,"createdIndex":430},{"key":"/messages","dir":true,"modifiedIndex":463,"createdIndex":463},{"key":"/queue","dir":true,"modifiedIndex":4633,"createdIndex":4633},{"key":"/notifications","dir":true,"modifiedIndex":7139,"createdIndex":7139},{"key":"/networks","dir":true,"modifiedIndex":382,"createdIndex":382},{"key":"/indexes","dir":true,"modifiedIndex":127,"createdIndex":127},{"key":"/clusters","dir":true,"modifiedIndex":669,"createdIndex":669},{"key":"/nodes","dir":true,"modifiedIndex":8,"createdIndex":8}]}}
```

**Comment by GowthamShanmugam** [comment]
@mbukatov @r0h4n 
i feel ETCD_CA_FILE should be changed as ETCD_TRUSTED_CA_FILE, because i dont see ETCD_CA_FILE in etcd.conf file

**Comment by r0h4n** [comment]
@GowthamShanmugam Done, thanks

https://github.com/Tendrl/documentation/wiki/Tendrl-with-a-secure-etcd-cluster

**Comment by mbukatov** [comment]
Status update: work as been done on all blocker issues. I'm going to fully retest new snapshot builds when we have our lab back online.

**Comment by mbukatov** [comment]
I'm going to report issue with tls etcd auth and move to using fqdn everywhere instead of ip addresses, as discussed with Rohan today.

**Comment by mbukatov** [comment]
Related issue: https://github.com/Tendrl/commons/issues/759

**Comment by mbukatov** [comment]
Implemented by https://github.com/Tendrl/tendrl-ansible/pull/54
