### ISSUE TITLE
Implement cluster unmanage feature via ansible

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/tendrl-ansible#50]
This is a proposal for implementing **cluster unmanage** feature via tendrl-ansible. This feature consists of ~two~ one step, which we could consider to perform on it's own (for dev/testing purpose):

* remove tendrl components from the storage machines without interference with storage system
* ~delete the cluster from tendrl central store, so that tendrl is no longer aware of it~ (feature removed based on https://github.com/Tendrl/tendrl-ansible/issues/50#issuecomment-334050711)

## FAQ

How it will be implemented? Most likely it would be a playbook for people to tweak and reuse.

Will this be officially tested and supported? No, qe team declined testing of this feature. It is something targeted to dev, qe and knowledgeable admins who are on their own.

Wouldn't it be better to implement something like this in tendrl directly? Yes, it would, but this feature is not going to be implemented in tendrl in  a near future, and we may still find this useful to be implemented here instead.

## Questions

There is new description of tendrl uninstallation in https://github.com/Tendrl/documentation/wiki/Tendrl-release-v1.5.4-(install-guide)#uninstall-tendrl

To reliably implement this feature, we need to know exactly:

* [ ] which services, in which order to stop
* [ ] which packages to uninstall
* [ ] which directories to remove (eg. leftover cache, or database with previous state)
* [ ] clarify step when we say to optionaly backup and then delete etcd data (how to restore the backup after tendrl reinstall?)

**Comment by r0h4n** [comment]
Please add these tasks as well for unmanage 
- Set cluster.is_managed="no"
- Remove all objects/resources being tracked for this Cluster and Nodes in the cluster from graphite
- Remove collectd plugins installed on nodes in the cluster

In general, any interactions with the Tendrl central store should be done via Tendrl flows/api and not tendrl-ansible.

But removal of rpm packages can be done via tendrl-ansible

**Comment by mbukatov** [comment]
@r0h4n ack, unmanage can't be implemented via tendrl-ansible, but removal of tendrl rpm packages from storage machines is ok

**Comment by mbukatov** [comment]
There is new description of tendrl uninstallation in https://github.com/Tendrl/documentation/wiki/Tendrl-release-v1.5.4-(install-guide)#uninstall-tendrl

**Comment by mbukatov** [comment]
Accepting this feature for future upstream release 1.5.5

**Comment by mbukatov** [comment]
Based on [unmanage feature specification](https://github.com/Tendrl/specifications/pull/255), which is upcoming Tendrl feature, I'm closing this.
