### ISSUE TITLE
Rpm build using make rpm failed with tendrl-ansible-3.0’: File exists

### ISSUE THREAD

**Issue by TimothyAsirJeyasing** [Tendrl/tendrl-ansible#51]
Please remove the tendrl-ansible-3.0 directory once the srpm or dist tar is created.

**Comment by mbukatov** [comment]
Ah, I know what you have in mind. When I run `make dist` 2 times in a row, it fails on the error you reported:

```
$ make dist
mkdir tendrl-ansible-1.5.3
mkdir: cannot create directory ‘tendrl-ansible-1.5.3’: File exists
make: *** [Makefile:16: dist] Error 1
```

This target is a bit suboptimal (it can't make sure that only commited changes goes into the tarball), but it matches what we have in other tendrl repositories.

I could fix that by running a `clean` for every `dist` target. See bb369e4ab45ddeb9bdfa4aed521ac8f698254673 Would that be ok?

**Comment by TimothyAsirJeyasing** [comment]
LGTM

**Comment by mbukatov** [comment]
Fixed by https://github.com/Tendrl/tendrl-ansible/commit/bb369e4ab45ddeb9bdfa4aed521ac8f698254673
