### ISSUE TITLE
Update prechecks playbook to match new requirements

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/tendrl-ansible#65]
Sence hw requirements (wrt cpu and memory) in installation guide were updated, we need to update prechecks playbook to match what is stated there.

I don't link to the particular values, as the next release 1.5.5 is not currently finalized and numbers could change.

**Comment by r0h4n** [comment]
Please check latest release 1.5.5 and update prechecks (4vcpu, 16gb memory)

https://github.com/Tendrl/documentation/wiki/Tendrl-release-v1.5.5-(install-guide)#tendrl-server-system-requirements

**Comment by r0h4n** [comment]
@mbukatov Any updates?  There's been a lot of ask for removing the memory and (v)cpu pre-checks.  Could you please remove them in this Milestone 3 (2018)

**Comment by cybernth** [comment]
> I don't link to the particular values, as the next release 1.5.5 is not currently finalized and numbers could change.

I suggest we update the playbook with currently reccomended configuration. We can update later if there is any change. @mbukatov

**Comment by mbukatov** [comment]
Ack, the current requirements are here https://github.com/Tendrl/documentation/wiki/Tendrl-release-v1.6.0-(install-guide)#tendrl-server-system-requirements and I assume we are not going to change it for milestone 3.

**Comment by mbukatov** [comment]
Implemented by https://github.com/Tendrl/tendrl-ansible/pull/81
