### ISSUE TITLE
Change default value for selinux_mode

### ISSUE THREAD

**Issue by cybernth** [Tendrl/tendrl-ansible#66]
update the playbooks, README etc to set the selinux value defaulted to `enforcing`

**Comment by mbukatov** [comment]
It would be even better to drop task setting SELinux mode entirely.

**Comment by mbukatov** [comment]
> It would be even better to drop task setting SELinux mode entirely.

Like this: https://github.com/Tendrl/tendrl-ansible/pull/76

Since we now have basic SELinux support, one no longer need to touch SELinux configuration in order to install Tendrl. So from maintenance perspective, it seems better to remove this code entirely.

**Comment by mbukatov** [comment]
Fixed by https://github.com/Tendrl/tendrl-ansible/pull/76
