### ISSUE TITLE
rsyslog requires a reload after node-agent installation

### ISSUE THREAD

**Issue by cybernth** [Tendrl/tendrl-ansible#67]
node-agent installation adds a new rsyslog configuration file. Hence rsyslog needs to be releaded to load the node-agent logging configuration

**Comment by TimothyAsirJeyasing** [comment]
Hope the restart of rsyslog will create /var/log/tendrl/node-agent directory which is required for logging.
Currently this directory is created only on reboot of the machine.

**Comment by mbukatov** [comment]
I need to investigate if this is a bug in rpm specfile first.

**Comment by cybernth** [comment]
@TimothyAsirJeyasing , On reboot during the rsyslog startup the new config file is loaded and the directory created. You can test this out by simply restart/reload the rsyslog service

**Comment by mbukatov** [comment]
There seems to be no direct suggestion for restarting rsyslog in rpm scriptlet, so I'm ok with adding this into tendrl-ansible. That said, we could end up moving it into spec file later if there is a good reason for this (I would rather add it into a spec file, but I need to ask someone with more packaging experience first).

**Comment by mbukatov** [comment]
This is being implemented as https://github.com/Tendrl/tendrl-ansible/pull/69

**Comment by mbukatov** [comment]
Fixed in https://github.com/Tendrl/tendrl-ansible/pull/69
