### ISSUE TITLE
Fix ansible setup failure if the system has more then one ip

### ISSUE THREAD

**Issue by TimothyAsirJeyasing** [Tendrl/tendrl-ansible#68]
During the installation of tendrl Web Administration, if the server has multiple active IP addresses, tendrl-ansible fails to execute the playbook and the installation fails.

**Comment by mbukatov** [comment]
Could you provide more details on what actually fails? Along with an example inventory file and playbook file?

**Comment by TimothyAsirJeyasing** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1518525

**Comment by mbukatov** [comment]
Based on today's _Discuss peding tendrl-nsible issues and plan_ meeting, we will address this problem by not providing any defaults in the playbook file, as described in https://github.com/Tendrl/tendrl-ansible/issues/74

**Comment by mbukatov** [comment]
Closing, will be addressed as part of https://github.com/Tendrl/tendrl-ansible/issues/74
