### ISSUE TITLE
Unique machine id precheck not required

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/tendrl-ansible#71]
tendrl-node-agents have long stopped requiring an unique machine id 

Is there any other reason for this check to exist?

https://github.com/Tendrl/tendrl-ansible/blob/master/prechecks.yml#L85

**Comment by mbukatov** [comment]
We can remove this check if machine id is no longer used. The check was implemented based on [TEN-257](https://tendrl.atlassian.net/browse/TEN-257).

That said, [search for machine id shows me few results](https://github.com/search?p=1&q=org%3ATendrl+machine+id&type=Code), so we may also need to remove it elsewhere.

**Comment by mbukatov** [comment]
Resolved by https://github.com/Tendrl/tendrl-ansible/pull/78
