### ISSUE TITLE
Reload httpd configuration after expand the cluster

### ISSUE THREAD

**Issue by TimothyAsirJeyasing** [Tendrl/tendrl-ansible#77]
tendrl-ansible start httpd service as it should however there's no reload of configuration, hence when cluster is expanded no RHGSWA UI is running, the same for graphite.

This issue occurs in the following situation
1. remove RHGSWA via Monitoring Guide - Unmanage Cluster steps
2. install RHGSWA again using tendril-ansible
RHGSWA UI is not running, Graphite UI is not running

The ansible should take care of running both RHGSWA UI and Graphite UI

**Comment by TimothyAsirJeyasing** [comment]
Details: https://bugzilla.redhat.com/show_bug.cgi?id=1526343

**Comment by mbukatov** [comment]
Closing based on comment from Luboš (https://bugzilla.redhat.com/show_bug.cgi?id=1526343#c4).
