### ISSUE TITLE
tendrl-ansible should meet requirements from TEN-257

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/tendrl-ansible#8]
This issue covers all requirements from [TEN-257](https://tendrl.atlassian.net/browse/TEN-257), with exception of pre checks (there is a separate issue for that).

* [X] The system will install and configure the core Tendrl components according to the upstream RPM documentation
* [x] ~The playbook should print out that the API admin password has been placed in /root/password on the main tendrl node and the permissions should be 700 on that file. It should not echo out the admin password (so that logging could not capture it).~
* ~The resulting Tendrl server(s) & performance monitoring server(s) will be able to manage both Ceph and Gluster nodes.~
* [X] All roles should be able to be converged on one node (but not storage clusters themselves)
* [x] ~If a storage node is already running ceph or gluster, the resulting node agent on that node will be setup as per the upstream docs for node-agent (the Tendrl system should handle the rest)~
* (Nice to have - not required) The playbook should have tags for the various aspects it does: --tags "precheck,configuration,packages" so that they can be skipped or run alone as desired (example use case: only run precheck, or re-run configuration)
   * [x] tag `rpm-installation` (but this is useful for testing or development only, no production usage expected - testing that one can install all packages from current repositories)
   * [x] tag `service-started` and `service-enabled` (making sure all services are enabled or running as expected)
   * [x] tag `firewalld` for firewalld related tasks
   * tag `configuration` is not a good idea, to reconfigure tendrl cluster, update playbook and run it again
   * tag for prechecks is not needed, as all the checks are in a separate playbook file
   * another option is to have tags for particular components, eg. `tendrl-ui` (again, useful mainly for testing/development)
* [x] The system runs these basic pre-checks on all nodes to ensure best practices are followed: https://github.com/Tendrl/tendrl-ansible/issues/7

Items which are striked out are no longer possible to implement in tendrl-ansible as originally intended because of recent changes in Tendrl itself.

**Comment by mbukatov** [comment]
Since the pre checks are available in a separate playbook, it can be run standalone. The last missing feature for this issue to be closed are [ansible tags](https://docs.ansible.com/ansible/latest/playbooks_tags.html) for all tasks. See also: [ansible best prectices](https://docs.ansible.com/ansible/latest/playbooks_best_practices.html).

**Comment by mbukatov** [comment]
@julienlim I will add tags for `service-started` and `service-enabled` so that one would be able to run just tasks related to that, quickly checking if everything is up and running without waiting for other tasks to finish

**Comment by julienlim** [comment]
Ack @mbukatov.  👍

**Comment by mbukatov** [comment]
Last missing pieces added in https://github.com/Tendrl/tendrl-ansible/pull/109.
