### ISSUE TITLE
[RFE] Provide an example default inventory file that is included with tendrl-ansible

### ISSUE THREAD

**Issue by julienlim** [Tendrl/tendrl-ansible#84]
It would improve ease-of-use if tendrl-ansible include an example inventory files.  See this inventory file example from openshift-ansible: https://github.com/openshift/openshift-ansible/blob/master/inventory/hosts.example.

Initially, we could have an all-in-one (simple) inventory file where all of tendrl server is on the same node, and then later include other examples for splitting out etcd, graphite, etc.

Thoughts?

@mbukatov

**Comment by mbukatov** [comment]
> It would improve ease-of-use if tendrl-ansible include an example inventory files.

This is a good idea. The question is how much details do we want to have there in comments?

> Initially, we could have an all-in-one (simple) inventory file where all of tendrl server is on the same node, and then later include other examples for splitting out etcd, graphite, etc.

Given current implementation, splitting things out of tendrl server would require some updates of the server role and the playbook.

**Comment by julienlim** [comment]
@mbukatov Let's address the all-in-one or simple scenario first, and over time, we can expand on this.  The idea is to make this easier for onboarding Tendrl.

**Comment by mbukatov** [comment]
I started with a minimal example (see the pull request), based on what we have in the readme file. We could add much more, but I start to worry about duplication of the descriptions for ansible variables we have ... I need to check how other ansible installer projects handles documentation.

**Comment by mbukatov** [comment]
Minimal example added in https://github.com/Tendrl/tendrl-ansible/pull/86, long term solution suggested in https://github.com/Tendrl/tendrl-ansible/issues/92
