### ISSUE TITLE
Should we be using el6 build of grafana by default?

### ISSUE THREAD

**Issue by shirshendu** [Tendrl/tendrl-ansible#93]
https://github.com/Tendrl/tendrl-ansible/blob/185791e23897990c00f3f06f91e855e2bf2a8225/roles/tendrl-ansible.grafana-repo/files/grafana.repo#L3

**Comment by mbukatov** [comment]
This is [based on installation docs](https://github.com/Tendrl/documentation/wiki/Tendrl-release-v1.6.2-(install-guide)#tendrl-server-installation) and if I recall right, this particular el6 url was used as [there was no el7 repository available at the time](https://web.archive.org/web/20170922041130/http://docs.grafana.org:80/installation/rpm/). But [now it seems that the el7 builds are available](http://docs.grafana.org/installation/rpm/#install-via-yum-repository):

> baseurl=https://packagecloud.io/grafana/stable/el/7/$basearch

I'm ok with updating it, but that let's ask @r0h4n and @nthomas-redhat when it's a good time for this.

That said, the el6 string in the url was more just a name, and the builds there provided (at least minimal) el7 support, eg. systemd service files (which are useful only with el7 onwards).

**Comment by mbukatov** [comment]
Either way, good catch.

**Comment by r0h4n** [comment]
Please go ahead with this, this will need to be tested and verified

**Comment by mbukatov** [comment]
Fixed. Note that this doesn't change grafana package in any way, both el 6 and el 7 repositories are the same.
