### ISSUE TITLE
Default tunables in tendrl-ansible for etcd

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/tendrl-ansible#96]
The default settings in etcd should work well for installations on a local network where the average network latency is low. 

Uncomment and set the values to following attributes in `/etc/etcd/etcd.conf` file:

```
   ETCD_MAX_SNAPSHOTS="2"
   ETCD_SNAPSHOT_COUNT="5000"
   ETCD_HEARTBEAT_INTERVAL="10000"
   ETCD_ELECTION_TIMEOUT="50000"
```

**Comment by GowthamShanmugam** [comment]
@r0h4n @nthomas-redhat @shtripat @shirshendu @mbukatov

**Comment by cybernth** [comment]
@mbukatov , https://coreos.com/etcd/docs/latest/tuning.html for deatils about why we are reccomending  this

**Comment by mbukatov** [comment]
Implemented in 696eda1(already merged in master).

**Comment by mbukatov** [comment]
@nthomas-redhat should I cherry pick this into release/1.6.3 branch?

**Comment by r0h4n** [comment]
@mbukatov  You can bump up the release number and merge master onto release/1.6.3
